# Generated by Django 3.2.5 on 2022-05-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Airline_name', models.CharField(choices=[('EGA', 'Egypt Air'), ('NIA', 'Nile Air'), ('ARA', 'Arabic Air')], default='Egypt Air', max_length=15)),
                ('From', models.CharField(choices=[('CAI', 'Cairo Airport'), ('HGR', ' Hurghada Airport'), ('HBE', 'Borg El Arab Airport'), ('SSH', 'Sharm El Sheikh Airport')], default='Cairo Airport', max_length=30)),
                ('To', models.CharField(choices=[('CAI', 'Cairo Airport'), ('HGR', ' Hurghada Airport'), ('HBE', 'Borg El Arab Airport'), ('SSH', 'Sharm El Sheikh Airport')], default='Hurghada Airport', max_length=30)),
                ('Depart', models.DateTimeField()),
                ('Price', models.FloatField()),
            ],
        ),
    ]
