# Generated by Django 3.2.5 on 2022-05-25 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Airline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='Capacity',
            field=models.IntegerField(default=30),
        ),
        migrations.CreateModel(
            name='Flight_Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickets', models.IntegerField()),
                ('Flight_Info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Airline.flights')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
