version: "3.8"

services:
  db:
    image: mysql:5.7
    container_name: safarbangla_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: safarbangla
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    
  web:
    build: .
    container_name: safarbangla_web
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:

