# Generated by Django 3.2.5 on 2022-04-17 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rnum', models.IntegerField(unique=True)),
                ('Rcategory', models.CharField(choices=[('SIG', 'Single'), ('DOB', 'Double'), ('DEX', 'Deluxe')], max_length=3)),
                ('Descrption', models.CharField(max_length=550)),
                ('Cap', models.IntegerField()),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Reserve_Rom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rcheck_in', models.DateTimeField()),
                ('Rcheck_out', models.DateTimeField()),
                ('Room', models.ForeignKey(default='100', on_delete=django.db.models.deletion.CASCADE, to='UserAccount.rom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='default.jpg', upload_to='profile_pics/')),
                ('vip', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
