# Generated by Django 3.2.5 on 2022-04-18 00:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserAccount', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reserve_Rom',
            new_name='Reserve_Room',
        ),
        migrations.RenameModel(
            old_name='Rom',
            new_name='Room',
        ),
    ]
