# Generated by Django 3.2.5 on 2022-05-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0003_auto_20220518_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='amount_to_pay',
            field=models.IntegerField(default=0),
        ),
    ]
