# Generated by Django 3.2.5 on 2022-05-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='Hname',
            field=models.CharField(choices=[('FRS', 'Four Season'), ('HIL', 'Hilton'), ('MAR', 'Marriot')], default='Hilton', max_length=20),
        ),
    ]
